variables:
  HEROKU_DEV_APP_NAME: polymail-development
  HEROKU_PROD_APP_NAME: polymail-teams

image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - deploy_dev
  - deploy_prod

deploy_dev:
  stage: deploy_dev
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_DEV_APP_NAME --api-key=$HEROKU_API_KEY
  environment:
    name: develop
    url: https://polymail-development.herokuapp.com/

  only:
    - develop

deploy_prod:
  stage: deploy_prod
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
  environment:
    name: develop
    url: https://teams.polymail.com
  needs: []
  when: manual
  only:
    - develop
