import Head from 'next/head'
import { Inter } from 'next/font/google'
import {
  Flex,
  Input,
  InputGroup,
  InputLeftElement,
  InputRightElement,
  Icon,
  Badge,
  Menu,
  MenuButton, MenuList, MenuItem
} from '@chakra-ui/react'
import styles from '@/styles/Home.module.css'
import {ChevronDownIcon, SearchIcon} from "@chakra-ui/icons";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Flex className={styles.header} w='100%' align={'center'}>
          <div className={styles.headerLogo}>
            <img src="/image/logo.png" alt=""/>
          </div>
          <Flex className={styles.headerTabs} align={'center'}>
            <Flex align={'center'} className={styles.tabsActive}>
              <Icon viewBox="0 0 20 20" fill="none">
                <path d="M3.96094 6.45964C3.96094 5.53916 4.70713 4.79297 5.6276 4.79297H14.3776C15.2981 4.79297 16.0443 5.53916 16.0443 6.45964V13.543C16.0443 14.4635 15.2981 15.2096 14.3776 15.2096H5.6276C4.70713 15.2096 3.96094 14.4635 3.96094 13.543V6.45964Z" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M4.58594 5.41797L10.0026 10.2096L15.4193 5.41797" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </Icon>
              Inbox
            </Flex>
            <Flex align={'center'}>
              <Icon viewBox="0 0 20 20" fill="none">
                <path d="M16.0443 14.3776V8.1276C16.0443 7.20713 15.2981 6.46094 14.3776 6.46094H3.96094V14.3776C3.96094 15.2981 4.70713 16.0443 5.6276 16.0443H14.3776C15.2981 16.0443 16.0443 15.2981 16.0443 14.3776Z" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M11.2526 6.2526L10.4764 4.82952C10.1844 4.29408 9.6231 3.96094 9.01319 3.96094H5.6276C4.70713 3.96094 3.96094 4.70713 3.96094 5.6276V9.16927" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </Icon>
              Projects
            </Flex>
          </Flex>
          <div className={styles.headerSearch}>
            <InputGroup>
              <InputLeftElement pointerEvents='none'>
                <SearchIcon />
              </InputLeftElement>
              <Input type='text' placeholder='Search' />
              <InputRightElement>
                <div className={styles.inputRight}>
                  ⌘K
                </div>
              </InputRightElement>
            </InputGroup>
          </div>

          <div className={styles.notificationBadge}>
            <Flex align={'center'} justify={'center'} className={styles.notificationIcon}>
              <Icon viewBox="0 0 11 17" fill="none">
                <path d="M0.879883 9.37793C0.879883 9.21387 0.948242 9.07031 1.07129 8.91992L7.44922 1.01758C7.94141 0.40918 8.71387 0.805664 8.43359 1.55078L6.34863 7.15625H10.3135C10.6143 7.15625 10.833 7.36133 10.833 7.64844C10.833 7.80566 10.7715 7.94922 10.6484 8.10645L4.26367 16.0088C3.77148 16.6104 2.99902 16.2139 3.2793 15.4688L5.36426 9.87012H1.39941C1.09863 9.87012 0.879883 9.6582 0.879883 9.37793Z" fill="#002871"/>
              </Icon>
              <Badge>3</Badge>
            </Flex>
          </div>

          <div className={styles.profile}>
            <Menu>
              <MenuButton rightIcon={<ChevronDownIcon />}>
                <img src="/image/user.png" alt=""/>
              </MenuButton>
              <MenuList>
                <MenuItem>Download</MenuItem>
                <MenuItem>Create a Copy</MenuItem>
                <MenuItem>Mark as Draft</MenuItem>
                <MenuItem>Delete</MenuItem>
                <MenuItem>Attend a Workshop</MenuItem>
              </MenuList>
            </Menu>
          </div>

        </Flex>
        {/*<div className={styles.description}>*/}
        {/*  <p>*/}
        {/*    Get started by editing&nbsp;*/}
        {/*    <code className={styles.code}>src/pages/index.tsx</code>*/}
        {/*  </p>*/}
        {/*  <div>*/}
        {/*    <a*/}
        {/*      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
        {/*      target="_blank"*/}
        {/*      rel="noopener noreferrer"*/}
        {/*    >*/}
        {/*      By{' '}*/}
        {/*      <Image*/}
        {/*        src="/vercel.svg"*/}
        {/*        alt="Vercel Logo"*/}
        {/*        className={styles.vercelLogo}*/}
        {/*        width={100}*/}
        {/*        height={24}*/}
        {/*        priority*/}
        {/*      />*/}
        {/*    </a>*/}
        {/*  </div>*/}
        {/*</div>*/}

        {/*<div className={styles.center}>*/}
        {/*  <Image*/}
        {/*    className={styles.logo}*/}
        {/*    src="/next.svg"*/}
        {/*    alt="Next.js Logo"*/}
        {/*    width={180}*/}
        {/*    height={37}*/}
        {/*    priority*/}
        {/*  />*/}
        {/*</div>*/}

        {/*<div className={styles.grid}>*/}
        {/*  <a*/}
        {/*    href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
        {/*    className={styles.card}*/}
        {/*    target="_blank"*/}
        {/*    rel="noopener noreferrer"*/}
        {/*  >*/}
        {/*    <h2>*/}
        {/*      Docs <span>-&gt;</span>*/}
        {/*    </h2>*/}
        {/*    <p>*/}
        {/*      Find in-depth information about Next.js features and&nbsp;API.*/}
        {/*    </p>*/}
        {/*  </a>*/}

        {/*  <a*/}
        {/*    href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
        {/*    className={styles.card}*/}
        {/*    target="_blank"*/}
        {/*    rel="noopener noreferrer"*/}
        {/*  >*/}
        {/*    <h2>*/}
        {/*      Learn <span>-&gt;</span>*/}
        {/*    </h2>*/}
        {/*    <p>*/}
        {/*      Learn about Next.js in an interactive course with&nbsp;quizzes!*/}
        {/*    </p>*/}
        {/*  </a>*/}

        {/*  <a*/}
        {/*    href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
        {/*    className={styles.card}*/}
        {/*    target="_blank"*/}
        {/*    rel="noopener noreferrer"*/}
        {/*  >*/}
        {/*    <h2>*/}
        {/*      Templates <span>-&gt;</span>*/}
        {/*    </h2>*/}
        {/*    <p>*/}
        {/*      Discover and deploy boilerplate example Next.js&nbsp;projects.*/}
        {/*    </p>*/}
        {/*  </a>*/}

        {/*  <a*/}
        {/*    href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
        {/*    className={styles.card}*/}
        {/*    target="_blank"*/}
        {/*    rel="noopener noreferrer"*/}
        {/*  >*/}
        {/*    <h2>*/}
        {/*      Deploy <span>-&gt;</span>*/}
        {/*    </h2>*/}
        {/*    <p>*/}
        {/*      Instantly deploy your Next.js site to a shareable URL*/}
        {/*      with&nbsp;Vercel.*/}
        {/*    </p>*/}
        {/*  </a>*/}
        {/*</div>*/}
      </main>
    </>
  )
}
