export const PROJECT_ROLES = ['member', 'admin'];
export const POSITION_GAP = 65535;
export const HEADER_NOT_ALLOWED_PATHS = ['/onboarding', '/onboarding/connect-account', '/onboarding/complete-profile'];
export const MAILBOX_INBOX = 'INBOX'
export const MAILBOX_DRAFT = 'DRAFT'
export const MAILBOX_UNREAD = 'UNREAD'
export const MAILBOX_ARCHIVE = 'ARCHIVE'
export const MAILBOX_TRASH = 'TRASH'
export const MAILBOX_SNOOZED = 'SNOOZED'
export const MAILBOX_STARRED = 'STARRED'
